### ISSUE TITLE
Missunderstanding of the big O notation

### ISSUE THREAD

**Issue by GrosSacASac** [amilajack/js-algorithms#57]
https://github.com/amilajack/js-algorithms/tree/master/Complexity

Examples of O(n^2)
=== inside a for loop: iterates over each char to check equality of each char

which is wrong.

Understanding the big O notation:
How much time does it take on average to compare with === for 1 item: Answer 1(unit of time)
How much time does it take on average to compare with === for 2 item: Answer 2(unit of time)
How much time does it take on average to compare with === for n item: Answer n(unit of time)

The big O notation answers how does it scale for a very big n, n being the size.
The big O notation does not answer if the algorithm takes a lot of time.

**Comment by amilajack** [comment]
Would appreciate a PR for this 😄
